### PR TITLE
Fix: Route from BindRequest not passed on

### PR DESCRIPTION
**Pull request by fabstu**
If there is a Route in the Bind Request then put it into the map instead of AppGUID again.

### CODE REVIEW

**Comment by fabstu** [comment]
I signed it

**Comment by jberkhahn** [comment]
Pretty sure this resource is part of route services, which Service Catalog doesn't currently support, or ever plan to. That doesn't necessarily that we should be sticking it in the app guide, but something to think about.

**Comment by jhvhs** [comment]
Good catch, thanks @fabstu 
/lgtm

**Comment by jhvhs** [comment]
> Pretty sure this resource is part of route services, which Service Catalog doesn't currently support, or ever plan to. That doesn't necessarily that we should be sticking it in the app guide, but something to think about.

Sorry @jberkhahn, I missed your message. I can't see why the library shouldn't follow [the spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#bind-resource-object), given that it supports all the rest of the fields required for the flow. Is it interfering in any way with the Service Catalog, or am I missing something?

/assign @jberkhahn

**Comment by jberkhahn** [comment]
Ok, but let it be on your head.
/approve

**Pull request merged**
