### PR TITLE
Preparation for v2 release

### LINKED ISSUE #157: Prepare repo for releasing v2.x.y
There has been some discussion around releasing a new version of go-open-service-broker-client and what version it should have. The point has been made that in order to be compliant with the import path `github.com/kubernetes-sigs/go-open-service-broker-client/v2` that we should release a version that is `v2.x.y`. However in order to do this in go modules it is usual to indicate this in the module defined in `go.mod` https://github.com/kubernetes-sigs/go-open-service-broker-client/blob/4406bd2cb6b8ace5644ce50f7d4c790da8e00219/go.mod#L1 by updating it to include a `/v2`. This would result in the actual import path becoming `github.com/kubernetes-sigs/go-open-service-broker-client/v2/v2` (since the libraries are currently in a `v2` subdirectory). There are two possible solutions to this:

1. Move the contents of `v2` to the top level and update `go.mod` to include `v2`
2. Make use of the "major version subdirectory strategy", see: https://blog.golang.org/v2-go-modules. This would entail moving `go.mod` and `go.sum` into the `v2` directory and updating the module name to include `/v2` at the end.

Once either of these is done we could cut a new release with `v2.x.y`.

### PR DESCRIPTION
**Pull request by edwardecook**
I continue to not have a strong preference between this implementation and moving the `v2` folder contents to the root directory but I thought I'd give implementing one of them a go to see what it looked like. I also switched the module path to follow the standard for repos in k8s sigs.

Resolves #157

### CODE REVIEW

**Comment by mszostok** [comment]
I also do not have a strong opinion if we should move the content to root dir or move **go.mod** inside the `/v2` package.

One thing that I want to know is what needs to be done if we want to have e.g. `v3` version?

If we will use the  "major version subdirectory strategy", we need to create a `v3` pkg and copy content there? or rename the package from `v2` to `v3`? as having multiple versions on master can be strange for me and maintain that e.g. for the same commit you can create a release with tag `v3.0.0` and `v2.0.0` as you still have two folders on the master 🤔 

and when all things will be moved to root dir then we can only change the version in go.mod from `v2` to `v3`? like one line change? or it's more complicated?

**Comment by edwardecook** [comment]
I think your assessment of the "major version subdirectory strategy" is correct in that if we wanted to bump to `v3` we would then have both `v2` and `v3` on master which seems weird to me. 

On the other hand switching to everything at the root dir would mean that if we bumped to `v3` then we would also need to maintain a `v2` branch for if changes needed to be made there, that said that is more of a normal flow.

**Comment by edwardecook** [comment]
PR with the alternative implementation: #162

**Comment by edwardecook** [comment]
I'm going to close this as #162 was merged and this was a different possible route.

**Pull request closed without merging**
