### PR TITLE
Add Version 2.14

### LINKED ISSUE #144: Add support for OSBAPI 2.14
We'd like to get this client up to date with the current version of the OSBAPI spec (which is currently on 2.15). This is an interim step to add support for 2.14.

Below is a list of the 2.14 release notes. We plan to look at each feature and determine if the feature has already been implemented or if new changes are required.

| Feature | Current Status |
| ------- | -------------- |
| Added Opaque Bearer Tokens to the [Platform to Service Broker Authentication](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#platform-to-service-broker-authentication) section ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/398)) | DONE | 
| Added [Content Type](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#content-type) guidelines  | DONE | 
| Added GET endpoints for fetching a [Service Binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-binding) | ALPHA | 
| Added support for asynchronous Service Bindings ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/334))and a new [last operation endpoint for Service Bindings](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#polling-last-operation-for-service-bindings) endpoint | ALPHA | 
| Added GET endpoints for fetching a [Service Instance](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-instance) | ALPHA (#145) | 
| Allow an updated `dashboard_url` to be provided when updating a Service Instance ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/437)) | ALPHA | 
| Added clarity around concurrent updates ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/300)) | N/A | 
| Added clarity on how Platform's can clean up after a failed provision or bind ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/353)) | N/A | 
| Provided guidance for CLI-friendly names ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/425)) | N/A | 
| Allow for uppercase characters in Service and Service Plan names ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/433)) | N/A | 
| Clarify that extra fields in requests and responses are allowed ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/436)) | N/A | 
| Added an [OpenAPI 2.0 implementation](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/openapi.yaml) |  N/A | 
| Allow for periods in name fields ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/452)) | N/A | 
| Removed the need for Platforms to perform orphan mitigation when receiving an `HTTP 408` response code ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/456)) | N/A | 
| Moved the `dashboard_client` field to [Cloud Foundry Catalog Extensions](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/profile.md#cloud-foundry-catalog-extensions) | N/A | 
| Added a [compatibility matrix](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/compatibility.md) describing which optional features in the specification are supported by different Platforms | N/A | 
| Added clarity for returning Service Binding information via the GET endpoints ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/517))  | N/A | 
| Added guidance for supported string lengths ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/518))  | N/A | 
| Clarified that the `plan_updateable` field affects modifying the Service Plan, not parameters ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/519))  | N/A | 
| Clarified which Service Plan ID to use for polling the last operation endpoint after an update ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/522))  | N/A | 
| Clarified Platform behaviour when a dashboard URL is not returned ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/527))  | N/A | 
| Fixed an incompatible change introduced in v2.12 ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/540))  | N/A | 
| Added clarity around the state of resources after a failure ([PR](https://github.com/openservicebrokerapi/servicebroker/pull/541))  | N/A | 

* `DONE` = Feature is released
* `ALPHA` = implemented behind feature flag
* `WORK REQUIRED` = not currently implemented - requires work
* `N/A` = no changes required to client

In terms of implementation we were thinking to PR in new features as `Alpha` features, then once we think everything has been implemented we can open a final PR to move the features from `Alpha` and add `Version2_14` to the client.

Does that all sound reasonable?

Thanks
@tedddyking and @samze

### PR DESCRIPTION
**Pull request by edwardecook**
Includes graduating all the previously alpha features.

closes #144

### CODE REVIEW

**Comment by edwardecook** [comment]
The test coverage loss is primarily due to some methods associated with alpha features not being in use any more, I suppose they could be removed and added back when the next alpha feature is added but that seems somewhat pointless.

**Comment by edwardecook** [comment]
It would be great to get an update on what is holding this PR back, OSBAPI is approaching releasing a v2.16 (https://github.com/openservicebrokerapi/servicebroker/pull/710) which would put this repo 3 versions out of date.

**Comment by edwardecook** [comment]
Hi @mszostok thanks for the review, I realised there were a bunch of other spots that still erroneously referred to features being ALPHA API only. There are three usages that I haven't touched as part of this PR, one was resolved by https://github.com/kubernetes-sigs/go-open-service-broker-client/pull/148 and the other two would be resolved by https://github.com/kubernetes-sigs/go-open-service-broker-client/issues/153.

**Comment by mszostok** [comment]
thanks for taking care of that 👍 
/approve
/lgtm

**Pull request merged**
